# Lab 04. Numpy를 이용하여 이미지를 저장할 때, 효율 비교하기
---

In [1]:
!pip install Pillow

In [2]:
import numpy as np
from PIL import Image

- 이미지를 불러오고 그레이 스케일로 변환한다.

In [3]:
# 이미지 불러오기 
img = Image.open("./data/cat.png").convert('L')    # 그레이 스케일 변환
print(img)

<PIL.Image.Image image mode=L size=310x162 at 0x2AF3AE2DD88>


In [4]:
img_array = np.array(img)

print(img_array)

[[222 222 222 ... 169 169 169]
 [223 223 223 ... 168 168 168]
 [223 223 223 ... 165 165 165]
 ...
 [219 219 222 ... 235 234 234]
 [221 222 224 ... 236 236 235]
 [221 222 224 ... 236 236 235]]


- 이미지를 저장하고, 저장한 이미지를 불러와본다.

In [5]:
np.save("./data/pil_image.npy", img_array)

In [6]:
img_array1 = np.load("./data/pil_image.npy")

print(img_array1)

[[222 222 222 ... 169 169 169]
 [223 223 223 ... 168 168 168]
 [223 223 223 ... 165 165 165]
 ...
 [219 219 222 ... 235 234 234]
 [221 222 224 ... 236 236 235]
 [221 222 224 ... 236 236 235]]


- 다시 PIL 이미지로 변환한다.

In [7]:
# 다시 PIL 이미지로 변환 
img = Image.fromarray(np.uint8(img_array1))
img.save("./data/image_numpy.png")

- 각 이미지 파일의 용량을 불러와서 출력한다.

In [8]:
import os 

np_save_size = os.path.getsize("./data/pil_image.npy")
pil_save_size = os.path.getsize("./data/image_numpy.png")

print(np_save_size, "bytes")
print(pil_save_size, "bytes")

50348 bytes
26813 bytes
