# Lab 03. 텐서 기본 실습
---

In [1]:
import torch 
import numpy as np

## 텐서 초기화용 데이터를 이용하여 직접 텐서를 생성하기

In [2]:
# 1. torch 이용해서 만든 텐서 
data = [[1, 2], [3, 4]]
print(type(data))
x_data = torch.tensor(data)

print(x_data)

# 2. Numpy -> troch tensor 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

<class 'list'>
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


- `torch.tensor()`는 입력 텐서를 복사하여 새로운 텐서를 만든다. 
    - 이 함수는 항상 새로운 메모리를 할당하므로, 원본 데이터와의 메모리 공유가 이루어지지 않는다.
- `torch.from_numpy()` 함수는 NumPy 배열을 PyTorch 텐서로 변환할 때, 원본 데이터와의 메모리 공유를 유지한다.

In [3]:
x_ones = torch.ones_like(x_data) 
print(f"ones Tensor : \n{x_ones}")
# torch.ones_like()주어진 입력 텐서와 동일한 크기의 텐서를 생성하고 모든 요소를 1로 채우면 된다.


x_rand = torch.rand_like(x_data, dtype=torch.float)    # x_data 속성을 덮어쓴다.
print(f'Random Tensor : \n{x_rand}')
# torch.rand_like() 주어진 입력 텐서와 동일한 크기의 텐서를 생성하고 모든 요소를 랜덤한 값으로 채운다. 그리고 타입 지정하면 그 타입으로 변경된다.
# 0과 1사이의 랜덤한 값으로 초기화 되고, 데이터 타입 유형은 dtype=torch.float 지정된다.

ones Tensor : 
tensor([[1, 1],
        [1, 1]])
Random Tensor : 
tensor([[0.6899, 0.3164],
        [0.9167, 0.3233]])


In [4]:
# 무작위 또는 상수 값을 사용하기 
shape = (5,6,)
rand_tensor = torch.rand(shape) * 10    # 0 ~ 10 
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("rand_tensor \n", rand_tensor)
print("ones_tensor \n", ones_tensor)
print("zeros_tensor \n" , zeros_tensor)


# 유효 범위를 최소값 얼마 부터 ~ 최대값 얼마까지 6 ~ 10 
shape_temp = (5,6)
min_val = 6
max_val = 10 
rand_tensor_temp = torch.rand(shape_temp) * (max_val - min_val) + min_val
print(rand_tensor_temp)

rand_tensor 
 tensor([[5.0226, 1.0111, 6.3163, 9.7389, 2.8107, 0.2403],
        [4.5066, 8.2667, 7.4144, 9.9092, 1.6633, 7.2506],
        [3.0800, 2.7175, 4.5451, 5.2286, 6.1455, 9.9144],
        [6.7574, 3.5312, 7.6747, 4.7251, 8.4958, 3.4557],
        [7.2627, 0.1201, 2.8326, 0.7539, 9.5175, 6.4064]])
ones_tensor 
 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
zeros_tensor 
 tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[8.1119, 9.6542, 8.7367, 8.9440, 9.7202, 6.5612],
        [7.5630, 6.4580, 9.3568, 6.8211, 6.7240, 9.4957],
        [6.9931, 7.2989, 6.6578, 9.6498, 9.4660, 6.3368],
        [9.5675, 6.1532, 8.6557, 6.7643, 6.0697, 7.0283],
        [6.4958, 9.6567, 7.3969, 6.5392, 9.3496, 9.8410]])


## 텐서 속성 

In [5]:
tensor_val = torch.rand(3, 4)

# 디바이스 정보 가져오기 
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

# tensor_val.to("cuda")

# 디바이스 변경하고자 하는 경우 
# 텐서의 디바이스를 변경하려면 to() 메서드를 사용할 수 있습니다. 이 메서드는 새로운 디바이스로 텐서를 이동시킨다.
# EX) model.to(device)

print(f"Shape of tensor : {tensor_val.shape}")
print(f"Data type of tensor {tensor_val.dtype}")
print(f"Device tensor is stored on : {tensor_val.device}")

cpu
Shape of tensor : torch.Size([3, 4])
Data type of tensor torch.float32
Device tensor is stored on : cpu


In [6]:
# 표준 인덱싱 과 슬라이싱 
tensor_l = torch.ones(4, 4)
tensor_l[:,3] = 0

tensor_2 = torch.ones(4, 4)
tensor_2[:,1] = 2
print(tensor_l)
print(tensor_2)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])
tensor([[1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.]])


In [7]:
# 텐서 합치기 

t1 = torch.cat([tensor_l, tensor_l], dim=1)
print(t1)

tensor([[1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0.]])


In [8]:
t_mult = tensor_l.mul(tensor_2)
print(t_mult)

print(tensor_l * tensor_2)

tensor([[1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.]])
tensor([[1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.]])


In [9]:
# 행렬 곱 
print(tensor_2.matmul(tensor_2.T))
print(tensor_2 @ tensor_2.T)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])
tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])


In [10]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

t.add_(1)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## 뷰 (View) - 원소의 수를 유지하면서 텐서의 크기 변경 

In [11]:
"""
파이토치 텐서의 뷰는 넘파이의 Reshape 와 같은 역할
Reshape > 텐서의 크기를 변경해주는 역할 
"""

# 3차원 데이터 생성
t_temp = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
ft = torch.FloatTensor(t_temp)
print(ft)
print(ft.shape)

# 이제 ft view -> 2차원 텐서로 변경 
# -1 : 나는 그 값을 모르겠음 파이토치 니가 알아서 해 !! 두번째 차원은 길이는 3 가지도록 하라는 의미이다.  
print(ft.view([-1, 3])) # (?, 3)
print(ft.view([-1, 3]).shape)

# view() 메서드를 사용하여 텐서의 차원을 변경하면 -> 데이터를 복사하여 새로운 텐서를 생성하고, 이 새로운 텐서는 원래 텐서와 메모리를 공유하지 않는다.

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [14]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)


tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


- 스퀴즈는 차원이 1인 경우에는 해당 차원을 제거한다. 

In [15]:
# 3x1 크기를 가지는 2차원 텐서 생성
ft = torch.FloatTensor(([0], [1], [2]))
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [17]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


- 언스퀴즈 -> 특정 위치에서 1인 차원을 추가한다.

In [18]:
ft_temp = torch.Tensor([0, 1, 2])
print(ft_temp.shape)

torch.Size([3])


In [21]:
# 첫번째 차원에서 1차원 추가 
# 인덱스 0 
print(ft_temp.unsqueeze(0))
print(ft_temp.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [22]:
print(ft_temp.view(1, -1))
print(ft_temp.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])
